# Generated by Django 5.1.6 on 2025-03-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/media/receitas'),
        ),
    ]
