# Generated by Django 5.1.6 on 2025-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='media/perfis/default.jpg', upload_to='media/perfis/'),
        ),
    ]
